import { apiSlice } from './apiSlice';
import { ORDERS_URL } from '../Constant';

export const orderApiSlice = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    // Get all orders for logged-in user
    getOrders: builder.query({
      query: () => `${ORDERS_URL}`,
      providesTags: ['Orders'],
    }),

    // Get single order by orderId
    getOrderById: builder.query({
      query: (orderId) => `${ORDERS_URL}/${orderId}`,
      providesTags: (result, error, orderId) => [{ type: 'Orders', id: orderId }],
    }),

    // Create new order
    createOrder: builder.mutation({
      query: (orderData) => ({
        url: `${ORDERS_URL}`,
        method: 'POST',
        body: orderData,
      }),
      invalidatesTags: ['Orders'],
      invalidatesTags: ['Cart'], // invalidate to refetch

    }),

    // Update order status
    updateOrderStatus: builder.mutation({
      query: ({ orderId, status }) => ({
        url: `${ORDERS_URL}/${orderId}/status`,
        method: 'PUT',
        body: { status },
      }),
      invalidatesTags: (result, error, { orderId }) => [{ type: 'Orders', id: orderId }],
    }),
  }),
  overrideExisting: false,
});

// Export hooks generated by RTK Query
export const {
  useGetOrdersQuery,
  useGetOrderByIdQuery,
  useCreateOrderMutation,
  useUpdateOrderStatusMutation,
} = orderApiSlice;
